### ISSUE TITLE
ensemble.metsActive definition for more than two conditions may be problematic

### ISSUE THREAD

**Issue by timmccubbin** [biosustain/GRASP#86]
Lines 229-240 of loadEnsembleStructure define ensemble.metsActive differently when there are less or more than 2 conditions.

It appears to me that metsActive must equal metsBalanced/rows of the reduced Smatrix for the Jacobian to be square when checking stability of the model. Defining metsActive as any metabolite in any condition that does not have an upper bound of one allows metabolites that are not balanced but may vary between conditions, e.g. ATP, to be included and the resulting Jacobian not square.

**Comment by martamatos** [comment]
I'm not sure when exactly, but this has been fixed.
